// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by vst/generate_settings.py
#pragma once

#include <json.hpp>
#include <map>
#include <string>
#include <variant>
#include <vector>

namespace GeneratedSettings {

// ChordQuality enum (mirrors Python)
enum class ChordQuality { MAJOR, MINOR, DOM_7, MAJOR_7, MINOR_7, DIM_7, AUGMENTED, SUS_4, ADD_9 };

// ChordQualities helper namespace for UI
namespace ChordQualities {
inline constexpr int NUM_QUALITIES = 9;
inline const char* NAMES[NUM_QUALITIES] = {"Major",          "Minor",     "Dominant 7th",  "Major 7th", "Minor 7th",
                                           "Diminished 7th", "Augmented", "Suspended 4th", "Add 9"};
inline const char* ENUM_NAMES[NUM_QUALITIES] = {"MAJOR", "MINOR", "DOM_7", "MAJOR_7", "MINOR_7", "DIM_7", "AUGMENTED", "SUS_4", "ADD_9"};
}  // namespace ChordQualities

// BundledChordVoicings helper namespace for UI
namespace BundledChordVoicings {
inline constexpr int NUM_BUNDLED = 2;
inline const char* FILENAMES[NUM_BUNDLED] = {"om_108_chord_voicing_offsets.json", "om_108_chord_voicings.json"};
inline const char* DISPLAY_NAMES[NUM_BUNDLED] = {"OmniChord: Relative", "OmniChord: Fixed"};
}  // namespace BundledChordVoicings

struct RootPositionStyle {
    static constexpr const char* TYPE = "RootPositionChordStyle";
};

struct BundledFileStyle {
    static constexpr const char* TYPE = "BundledFileStyle";
    std::string filename;
};

struct FileStyle {
    static constexpr const char* TYPE = "FileStyle";
    std::string path;
};

struct Omni84Style {
    static constexpr const char* TYPE = "Omni84Style";
};

struct PlainAscendingStrumStyle {
    static constexpr const char* TYPE = "PlainAscendingStrumStyle";
};

struct OmnichordStrumStyle {
    static constexpr const char* TYPE = "OmnichordStrumStyle";
};

struct ButtonPerChordQuality {
    static constexpr const char* TYPE = "ButtonPerChordQuality";
    std::map<int, ChordQuality> notes;
    std::map<int, ChordQuality> ccs;
};

struct CCRangePerChordQuality {
    static constexpr const char* TYPE = "CCRangePerChordQuality";
    int cc;
};

struct MidiNoteButton {
    static constexpr const char* TYPE = "MidiNoteButton";
    int note;
};

struct MidiCCButton {
    static constexpr const char* TYPE = "MidiCCButton";
    int cc;
    bool is_toggle;
};

using ChordVoicingStyle = std::variant<RootPositionStyle, BundledFileStyle, FileStyle, Omni84Style>;
using StrumVoicingStyle = std::variant<PlainAscendingStrumStyle, OmnichordStrumStyle>;
using ChordQualitySelectionStyle = std::variant<ButtonPerChordQuality, CCRangePerChordQuality>;
using LatchToggleButton = std::variant<MidiNoteButton, MidiCCButton>;

struct DaemomnifySettings {
    std::string midi_device_name;
    int chord_channel;
    int strum_channel;
    double strum_cooldown_secs;
    double strum_gate_time_secs;
    int strum_plate_cc;
    ChordVoicingStyle chord_voicing_style;
    StrumVoicingStyle strum_voicing_style;
    ChordQualitySelectionStyle chord_quality_selection_style;
    LatchToggleButton latch_toggle_button;
    LatchToggleButton stop_button;

    static DaemomnifySettings defaults();
};

// JSON serialization
std::string toJson(const DaemomnifySettings& settings);
DaemomnifySettings fromJson(const std::string& json);
bool isValidJson(const std::string& json);

// nlohmann JSON conversion declarations
void to_json(nlohmann::json& j, const DaemomnifySettings& s);
void from_json(const nlohmann::json& j, DaemomnifySettings& s);

void to_json(nlohmann::json& j, const RootPositionStyle& s);
void from_json(const nlohmann::json& j, RootPositionStyle& s);
void to_json(nlohmann::json& j, const BundledFileStyle& s);
void from_json(const nlohmann::json& j, BundledFileStyle& s);
void to_json(nlohmann::json& j, const FileStyle& s);
void from_json(const nlohmann::json& j, FileStyle& s);
void to_json(nlohmann::json& j, const Omni84Style& s);
void from_json(const nlohmann::json& j, Omni84Style& s);
void to_json(nlohmann::json& j, const PlainAscendingStrumStyle& s);
void from_json(const nlohmann::json& j, PlainAscendingStrumStyle& s);
void to_json(nlohmann::json& j, const OmnichordStrumStyle& s);
void from_json(const nlohmann::json& j, OmnichordStrumStyle& s);
void to_json(nlohmann::json& j, const ButtonPerChordQuality& s);
void from_json(const nlohmann::json& j, ButtonPerChordQuality& s);
void to_json(nlohmann::json& j, const CCRangePerChordQuality& s);
void from_json(const nlohmann::json& j, CCRangePerChordQuality& s);
void to_json(nlohmann::json& j, const MidiNoteButton& s);
void from_json(const nlohmann::json& j, MidiNoteButton& s);
void to_json(nlohmann::json& j, const MidiCCButton& s);
void from_json(const nlohmann::json& j, MidiCCButton& s);

void to_json(nlohmann::json& j, const ChordVoicingStyle& v);
void from_json(const nlohmann::json& j, ChordVoicingStyle& v);
void to_json(nlohmann::json& j, const StrumVoicingStyle& v);
void from_json(const nlohmann::json& j, StrumVoicingStyle& v);
void to_json(nlohmann::json& j, const ChordQualitySelectionStyle& v);
void from_json(const nlohmann::json& j, ChordQualitySelectionStyle& v);
void to_json(nlohmann::json& j, const LatchToggleButton& v);
void from_json(const nlohmann::json& j, LatchToggleButton& v);

}  // namespace GeneratedSettings
