// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by generate_vst_params.py from DaemomnifySettings
#pragma once

#include <juce_audio_processors/juce_audio_processors.h>

namespace GeneratedParams {

namespace ChordChannelChoices {
inline const juce::StringArray choices = {"1", "2",  "3",  "4",  "5",  "6",  "7",  "8",
                                          "9", "10", "11", "12", "13", "14", "15", "16"};
}  // namespace ChordChannelChoices

namespace StrumChannelChoices {
inline const juce::StringArray choices = {"1", "2",  "3",  "4",  "5",  "6",  "7",  "8",
                                          "9", "10", "11", "12", "13", "14", "15", "16"};
}  // namespace StrumChannelChoices

namespace ChordVoicingStyleChoices {
inline const juce::StringArray labels = {"Root Position", "File", "Omni-84"};
inline const juce::StringArray values = {"RootPositionChordStyle", "FileStyle", "Omni84Style"};
}  // namespace ChordVoicingStyleChoices

namespace StrumVoicingStyleChoices {
inline const juce::StringArray labels = {"Plain Ascending", "Omnichord"};
inline const juce::StringArray values = {"PlainAscendingStrumStyle", "OmnichordStrumStyle"};
}  // namespace StrumVoicingStyleChoices

namespace ChordQualitySelectionStyleChoices {
inline const juce::StringArray labels = {"Note Per Quality", "CC Per Quality", "CC Range"};
inline const juce::StringArray values = {"NotePerChordQuality", "CCPerChordQuality",
                                         "CCRangePerChordQuality"};
}  // namespace ChordQualitySelectionStyleChoices

namespace LatchToggleButtonChoices {
inline const juce::StringArray labels = {"Note", "CC"};
inline const juce::StringArray values = {"MidiNoteButton", "MidiCCButton"};
}  // namespace LatchToggleButtonChoices

namespace StopButtonChoices {
inline const juce::StringArray labels = {"Note", "CC"};
inline const juce::StringArray values = {"MidiNoteButton", "MidiCCButton"};
}  // namespace StopButtonChoices

// Cached parameter pointers
struct Params {
    std::atomic<float>* chord_channel = nullptr;
    std::atomic<float>* strum_channel = nullptr;
    std::atomic<float>* strum_cooldown_secs = nullptr;
    std::atomic<float>* strum_gate_time_secs = nullptr;
    std::atomic<float>* strum_plate_cc = nullptr;
    struct ChordVoicingStyleParams {
        std::atomic<float>* chord_voicing_style = nullptr;
        void init(juce::AudioProcessorValueTreeState& apvts);
    } chord_voicing_style;
    struct StrumVoicingStyleParams {
        std::atomic<float>* strum_voicing_style = nullptr;
        void init(juce::AudioProcessorValueTreeState& apvts);
    } strum_voicing_style;
    struct ChordQualitySelectionStyleParams {
        std::atomic<float>* chord_quality_selection_style = nullptr;
        struct NoteperchordqualityParams {
            std::atomic<float>* note_mapping_major = nullptr;
            std::atomic<float>* note_mapping_minor = nullptr;
            std::atomic<float>* note_mapping_dom_7 = nullptr;
            std::atomic<float>* note_mapping_major_7 = nullptr;
            std::atomic<float>* note_mapping_minor_7 = nullptr;
            std::atomic<float>* note_mapping_dim_7 = nullptr;
            std::atomic<float>* note_mapping_augmented = nullptr;
            std::atomic<float>* note_mapping_sus_4 = nullptr;
            std::atomic<float>* note_mapping_add_9 = nullptr;
            void init(juce::AudioProcessorValueTreeState& apvts);
        } NotePerChordQuality;
        struct CcperchordqualityParams {
            std::atomic<float>* cc_mapping_major = nullptr;
            std::atomic<float>* cc_mapping_minor = nullptr;
            std::atomic<float>* cc_mapping_dom_7 = nullptr;
            std::atomic<float>* cc_mapping_major_7 = nullptr;
            std::atomic<float>* cc_mapping_minor_7 = nullptr;
            std::atomic<float>* cc_mapping_dim_7 = nullptr;
            std::atomic<float>* cc_mapping_augmented = nullptr;
            std::atomic<float>* cc_mapping_sus_4 = nullptr;
            std::atomic<float>* cc_mapping_add_9 = nullptr;
            void init(juce::AudioProcessorValueTreeState& apvts);
        } CCPerChordQuality;
        struct CcrangeperchordqualityParams {
            std::atomic<float>* cc = nullptr;
            void init(juce::AudioProcessorValueTreeState& apvts);
        } CCRangePerChordQuality;
        void init(juce::AudioProcessorValueTreeState& apvts);
    } chord_quality_selection_style;
    struct LatchToggleButtonParams {
        std::atomic<float>* latch_toggle_button = nullptr;
        struct MidinotebuttonParams {
            std::atomic<float>* note = nullptr;
            void init(juce::AudioProcessorValueTreeState& apvts);
        } MidiNoteButton;
        struct MidiccbuttonParams {
            std::atomic<float>* cc = nullptr;
            std::atomic<float>* is_toggle = nullptr;
            void init(juce::AudioProcessorValueTreeState& apvts);
        } MidiCCButton;
        void init(juce::AudioProcessorValueTreeState& apvts);
    } latch_toggle_button;
    struct StopButtonParams {
        std::atomic<float>* stop_button = nullptr;
        struct MidinotebuttonParams {
            std::atomic<float>* note = nullptr;
            void init(juce::AudioProcessorValueTreeState& apvts);
        } MidiNoteButton;
        struct MidiccbuttonParams {
            std::atomic<float>* cc = nullptr;
            std::atomic<float>* is_toggle = nullptr;
            void init(juce::AudioProcessorValueTreeState& apvts);
        } MidiCCButton;
        void init(juce::AudioProcessorValueTreeState& apvts);
    } stop_button;
    void init(juce::AudioProcessorValueTreeState& apvts);
};

// Create the parameter layout
juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();

}  // namespace GeneratedParams
